version: '3'

services:
  mongo:
    container_name: mongo
    image: mongo:4
    command: --replSet rs0
    ports:
      - '27017:27017'
      - '28017:28017'
    volumes:
      - ./data/mongo:/data/db
  redis:
    container_name: redis
    image: redis
    ports:
      - '6379:6379'
